### ISSUE TITLE
influx timeshift proxy container not starting exit 1 

### ISSUE THREAD

**Issue by rahulmr** [serputko/performance-testing-framework#10]
Hello,
I tried to run the front end stuff. **`docker-compose -f docker-compose-with-frontend.yml up -d`**
But I see that the influx timeshift proxy is not starting.
Here is the log.
```
-bash-4.2$ docker-compose -f docker-compose-with-frontend.yml up -d
Creating network "performance-testing-framework_default" with the default driver
Creating jmeter       ... done
Creating portainer    ... done
Creating telegraf                 ... done
Creating wptserver                ... done
Creating graphite                 ... done
Creating influxdb     ... done
Creating sitespeed.io             ... done
Creating docker-dind              ... done
Creating influxdb-timeshift-proxy ... done
Creating jenkins                  ... done
Creating wptagent                 ... done
Creating grafana                  ... done
Creating grafana-setup            ... done
-bash-4.2$ docker-compose -f docker-compose-with-frontend.yml ps
          Name                        Command               State                         Ports
--------------------------------------------------------------------------------------------------------------------
docker-dind                dockerd-entrypoint.sh            Up       2375/tcp
grafana                    bash -x /run1.sh                 Up       0.0.0.0:8857->3000/tcp
grafana-setup              /bin/sh -c /entrypoint.sh        Up
graphite                   /sbin/my_init                    Up       0.0.0.0:2003->2003/tcp, 2004/tcp, 2023/tcp,
                                                                     2024/tcp, 0.0.0.0:8080->80/tcp, 8125/udp,
                                                                     8126/tcp
influxdb                   /entrypoint1.sh                  Up       0.0.0.0:8653->8086/tcp, 8653/tcp
influxdb-timeshift-proxy   npm run start                    Exit 1
jenkins                    bash -x /run.sh                  Up       0.0.0.0:50000->50000/tcp,
                                                                     0.0.0.0:8181->8080/tcp
jmeter                     cat                              Exit 0
portainer                  /portainer                       Up       0.0.0.0:9000->9000/tcp
sitespeed.io               /start.sh -V                     Exit 0
telegraf                   bash -x /entrypoint1.sh te ...   Up       8092/udp, 8094/tcp, 8125/udp
wptagent                   /bin/bash /wptagent/entryp ...   Up       0.0.0.0:4001->80/tcp
wptserver                  docker-php-entrypoint /usr ...   Up       443/tcp, 0.0.0.0:80->80/tcp
-bash-4.2$ docker logs influxdb-timeshift-proxy

> influxdb-timeshift-proxy@0.0.8 start /influxdb-timeshift-proxy
> node ./bin/www

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/influxdb-timeshift-proxy/app.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! influxdb-timeshift-proxy@0.0.8 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the influxdb-timeshift-proxy@0.0.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2018-08-06T10_16_44_687Z-debug.log


```

Could you please check if there is an issue?

**Comment by rahulmr** [comment]
Environment details:
Linux: RHEL 7.4
Docker:

```

-bash-4.2$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: true


```
Docker-Compose 

```

-bash-4.2$ docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

**Comment by serputko** [comment]
Hi @rahulmr, thanks for reporting
fixed with https://github.com/serputko/performance-testing-framework/commit/71bde819b45c192fc1cb0a8a756486a96167ad8e

**Comment by rahulmr** [comment]
Thanks.
